export const POPULAR_MOVIES = "POPULAR_MOVIES";
export const TRENDING_ITEMS = "TRENDING_ITEMS";
export const TOP_RATED_MOVIES = "TOP_RATED_MOVIES";
export const NOW_PLAYING_MOVIES = "NOW_PLAYING_MOVIES";
export const UPCOMING_MOVIES = "UPCOMING_MOVIES";
